### ISSUE TITLE
Implement Circuit Relay v2 in JS

### ISSUE THREAD

**Issue by lidel** [libp2p/js-libp2p#1029]
go-ipfs 0.11 will ship with circuits v2, js-ipfs should be able to talk to them. 

Ref. https://github.com/libp2p/specs/blob/master/relay/circuit-v2.md

[Update 2023-01-05] In-progress PR:
https://github.com/libp2p/js-libp2p/pull/1533

https://github.com/libp2p/js-libp2p/issues/1029#tasklist-block-70c5c890-a1dc-436c-91b8-47f5543d0b27

**Comment by mpetrunic** [comment]
I would like to take this on. Should I rip circuit out of libp2p and develop it in separate repository?

**Comment by mpetrunic** [comment]
@achingbrain We agreed on a call to do it in a separate repo, but I just saw there is already https://github.com/libp2p/js-libp2p-circuit deprecated repo. Do you know why this stuff was pulled back into js-libp2p?
If we still wanna do it in a separate repo, should we unarchive this repo?

**Comment by mpetrunic** [comment]
cc @jacobheun maybe you can shed some light here.

**Comment by jacobheun** [comment]
@mpetrunic the original consolidation effort is at https://github.com/libp2p/js-libp2p/issues/384, and it links to a larger [discussion in js-ipfs](https://github.com/ipfs/js-ipfs/issues/2222). The main reasoning for pulling in these core modules to js-libp2p is to reduce the overhead of having to do independent releases and rollups for modules that don't provide any value as standalone modules. I don't think it makes much sense to have libp2p-circuit externalized to js-libp2p because I don't see it being used directly elsewhere, and it's just going to add overhead to feature/release cycles. If you want to do e2e testing with libp2p, that can also create additional testing overhead.

Unless there's something specific you're trying to achieve with it being a separate module, I'd recommend keeping it here to avoid the overhead. Circuit is pretty core to libp2p, regardless of environment, whereas some of the other standalone modules are arguably environment dependent customizations.

**Comment by mpetrunic** [comment]
Honestly, my only reasoning was that we could do it in typescript and ease in migration to typescript. Will open PR with circuit v2 on libp2p repo!

**Comment by mxinden** [comment]
:wave: libp2p steward, rust-libp2p maintainer here. I was involved in the final steps of the protocol design and implemented Circuit Relay v2 on the Rust side recently. Happy to help from the libp2p side, e.g. with deployments to test against. Unfortunately we don't have a test-suite you could develop against. @mpetrunic feel free to ping me here or on the various other communication channels.

**Comment by mpetrunic** [comment]
@mxinden Hey, tnx a lot for the offer, will ping you if I don't find anything. I'm currently struggling to get js-js test to pass 😅 
Do you have some interop setup in you use?

**Comment by mxinden** [comment]
> Do you have some interop setup in you use?

Unfortunately not. We are working on interop tests via https://github.com/testground/testground though that is still far from complete.

For now I can only offer Circuit Relay v2 deployments to test against @mpetrunic.

**Comment by vasco-santos** [comment]
@mpetrunic there are some interop tests go<->js via IPFS: https://github.com/ipfs/interop/tree/master/test/circuit 

You can link libp2p in that repo and test it

**Comment by p-shahi** [comment]
This is being taken up by @ckousik now, but for some reason set the assignee

**Comment by tinytb** [comment]
@ckousik Could we get an update on this issue? (at some regular cadence -- e.g. once a month would be fine)

**Comment by p-shahi** [comment]
For now this has been deprioritized in favor of go-libp2p WebRTC work per https://github.com/libp2p/go-libp2p/pull/1655#issuecomment-1319368953

**Comment by BigLep** [comment]
Reopening because there is followup work listed in https://github.com/libp2p/js-libp2p/pull/1533#pullrequestreview-1322333583

If we're tracking that somewhere else, please link and close.

**Comment by p-shahi** [comment]
Being tracked here: https://github.com/libp2p/js-libp2p/issues/1608
