### ISSUE TITLE
uTP

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#118]
There is a current implementation of utp but is not complete: https://github.com/libp2p/js-libp2p-utp

**Comment by diasdavid** [comment]
Revamp in progress https://github.com/libp2p/js-libp2p-utp/pull/74

**Comment by diasdavid** [comment]
> Context: This integration has been historically blocked on https://github.com/libp2p/js-libp2p-utp/issues/19

A bonus idea from a productive chat with @mafintosh today. We can actually enable libp2p-utp and other transports that don't do gracious closing just by removing the assumption that the transport do that and let the protocol that gets mounted on top assume that responsibility.

The reality is that almost every protocol on top of js-libp2p is already doing that.

**Comment by mkg20001** [comment]
> The reality is that almost every protocol on top of js-libp2p is already doing that.

The shim in my fix pr changes the close behaviour from "recieve or send close -> closes both sides" to "only send if the client aborts the source and ends the sink (pull-stream)". This assumes that the client using the transport uses another way to exchange a FIN message (as otherwise the "sink got closed" event never gets transmitted, thus leaving the connection open forever). Is that the case for multistream/libp2p?

**Comment by achingbrain** [comment]
Closing as https://github.com/libp2p/js-libp2p-utp exists (though is unmaintained). If this transport is still desirable, please continue further development in that repo.
