### ISSUE TITLE
Behavior of LIBP2P_FORCE_PNET

### ISSUE THREAD

**Issue by b1018043** [libp2p/js-libp2p#1189]
- **Version**: N/A

- **Platform**: N/A

- **Subsystem**: N/A

#### Description:

js-libp2p throw error when LIBP2P_FORCE_PNET is 0 and don't use Protector. Because, 0 (string) is true and js-libp2p enforce to use private network. However, go-libp2p don't throw an error when LIBP2P_FORCE_PNET is 0.

I think it should be that for intuitive dealing 
```
LIBP2P_FORCE_PNET=1        => enforce to use private network
LIBP2P_FORCE_PNET=true   => enforce to use private network

LIBP2P_FORCE_PNET=0        => not enforce to use private network
LIBP2P_FORCE_PNET=false  => not enforce to use private network
unset LIBP2P_FORCE_PNET  => not enforce to use private network
```
or if it should be the same as go-libp2p, it enforces to use of the private network when only LIBP2P_FORCE_PNET=1.

**Comment by BigLep** [comment]
2022-05-03 conversation: ultimately we want to be consistent with environment variable handling in the codebase (do we coerce numbers/strings to booleans?).  The current maintainers are not up on this and need to look into it since we don't use many environment variables.  

@b1018043: feel free to poke around for what other patterns you see in the codebase.

**Comment by BigLep** [comment]
2022-05-03 followup: @achingbrain will provide more comments.

**Comment by achingbrain** [comment]
See https://github.com/libp2p/js-libp2p/pull/1174#issuecomment-1116276348
