### ISSUE TITLE
Relay Storage

### ISSUE THREAD

**Issue by piboistudios** [libp2p/js-libp2p#1202]
https://github.com/libp2p/js-libp2p/blob/d16817ca443443e88803ee8096d45debb14af91b/src/circuit/circuit/hop.ts#L70

Does the TODO here refer to storing messages that cannot be delivered? (e.g. destination peer not online)

I am wondering because I'd like to implement this functionality for my own use cases and am not sure if this is where such logic should ultimately go, or if it fits better elsewhere

**Comment by achingbrain** [comment]
The current implementation is of Circuit Relay v1 - there's a v2 in the works here - https://github.com/libp2p/js-libp2p/pull/1166

It's going to ultimately replace v1 which will be removed since go-libp2p has no longer supports v1 so if you'd like to help out, getting the v2 PR up to speed is where your effort would be best directed.

**Comment by wemeetagain** [comment]
Closing in favor of #1166
No more changes will be made to relay v1 bc its being deprecated/removed.
