### ISSUE TITLE
Configuration page needs updates

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p#1228]
Issues seen while migrating lodestar to latest libp2p:

- configuration page references peer store "persistence", no longer an option, should use `PersistentPeerStore` instead
- `persistent: boolean` listed in an unused interface in `src/index.ts`
- `dialer: {...}` referenced in configuration page, should instead be under `connectionManager`
- ...

**Comment by achingbrain** [comment]
Hand-written docs do get out of sync from time to time.  Would you like to submit a PR that brings everything up to date?

**Comment by wemeetagain** [comment]
I have a branch in progress. waiting on a fix for https://github.com/bbc/typescript-docs-verifier/issues/22

**Comment by BigLep** [comment]
@wemeetagain : we're unblocked here now right?

**Comment by wemeetagain** [comment]
Yes this is unblocked.
It may be useful to break this work up into separate PRs since there's a lot of changes required.
I can start with `doc/CONFIGURATION.md`.

**Comment by maschad** [comment]
@wemeetagain I have a [draft PR here](https://github.com/libp2p/js-libp2p/pull/1505) to introduce [typescript-docs-verifier](https://github.com/bbc/typescript-docs-verifier) to check the [configs](https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md) , I'd be happy to help with updating the config docs f if you could point me to the branches you had started on. 

Given we will have generated docs once https://github.com/libp2p/js-libp2p/issues/1455 is closed, I don't think we would need to document some of the internal options and type descriptions.

@achingbrain do you think we should add [typescript-docs-verifier](https://github.com/bbc/typescript-docs-verifier) as a feature to [aegir](https://github.com/ipfs/aegir) in order to use it here?
