### ISSUE TITLE
Expose instance of libp2p to discovery instances

### ISSUE THREAD

**Issue by wanderer** [libp2p/js-libp2p#125]
It would be nice if the libp2p instance was exposed to discovery instances. For example I would like [libp2p-gossip-discovery](https://github.com/wanderer/js-libp2p-gossip-discovery) to follow the discovery interface, but it need access to the instances peerBook and `dail` to populate correctly.

**Comment by diasdavid** [comment]
We currently don't have a global namespace where any module can pick up on the properties of a libp2p node (from peerInfo, swarm etc). We can't really do that because how JS dep management works and how require behaves, however, we could use DI for it.

That said, you won't need any of the above to achieve your goal (thanks for providing an example). You just need to:

1. Create a libp2p node with a gossipDiscovery reference
2. gossipDiscovery.attach(libp2pInstance) (or method that does the same).

This way, gossipDiscovery would have access to all the dial/handle methods of a libp2p instance and libp2p would be able to receive the peers discovered by gossipDiscovery.

Makes sense?

**Comment by wanderer** [comment]
yep i think that makes sense
