### ISSUE TITLE
Unable to use `libp2p` with `ts-jest`

### ISSUE THREAD

**Issue by nickreynolds** [libp2p/js-libp2p#1356]
- **Version**:
0.37.3

- **Platform**:
Windows - Node.js

#### Severity:
High

#### Description:
When I attempt to include this project (or any related package, for that matter, such as `it-pipe`), I get a build error when trying to run my tests (using jest). I have only found this issue when importing packages related to `libp2p`. All other packages installed via npm have not had compatibility issues.

Building the project (via `tsc`) does not give any errors.

Specifically, the error I receive is:

``` 
FAIL  tests/libp2p.test.ts
  ● Test suite failed to run

    Cannot find module 'libp2p' from 'src/something.ts'

    Require stack:
      src/something.ts
      tests/libp2p.test.ts

    > 1 | import { createLibp2p } from "libp2p"
        | ^
      2 |
      3 | export default async function something() {
      4 |   const lib = await createLibp2p({})

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (src/something.ts:1:1)
```

#### Steps to reproduce the error:
Include this package (or any related package) in a project that uses jest, then attempt to test any piece of functionality of this (or related) package.

I have created a repository that I believe minimally reproduces the error:

https://github.com/nickreynolds/jest-libp2p

#### Other Notes
I assume there is some issue with the jest or typescript configuration? However I have not been able to find any useful information to resolve this.

**Comment by mpetrunic** [comment]
Your typescript is probably getting compiled to cjs. It would be best if you compiled to ESM code or maybe look into this: https://kulshekhar.github.io/ts-jest/docs/guides/esm-support/

**Comment by mpetrunic** [comment]
@nickreynolds It would seem that problem lies somewhere on ts-jest side so it might be worth opening issue there.
I've played around with your repo and:
- if I use tsc to compile src and tests and run `node --experimental-vm-modules ./node_modules/.bin/jest build/tests`, tests will pass
- uuid test is passing because uuid is not pure ESM module
- ts-jest doesn't seem to care about changes in tsconfig.json
- it's not really libp2p related and it probably makes more sense to have repo with some simpler, pure esm module, like it-pushable which fails with same error

I'm quite positive that there is bug somewhere in ts-jest module resolver
