### ISSUE TITLE
improve debug-print support for commonly used libp2p public datastructures

### ISSUE THREAD

**Issue by GlenDC** [libp2p/js-libp2p#1534]
- **Version**:

```
0.41.0
```

- **Platform**:

```
Darwin <redacted> 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64
```

- **Subsystem**:

All

#### Severity:

Low

#### Description:

In some environments, e.g. testground, it is common to print a lot of information regarding the code/system being tested. At the moment as it is however, js-libp2p is not very friendly towards this. A lot of its objects do not have a `toString` method provided or something similar, and as such print just an opaque 'object' message, not giving any info about its contents.

An example is when trying to make a ping test for libp2p. In that case I might want to print info about the peer, about the ongoing connection etc... For now a lot of types I have to transform via `JSON.stringify` first, so that I can print them in my recorded logs. Having these types be print-enabled (similar to or example how one makes sure that in Rust types are at the very least `Debug`'able (by implementing or deriving the trait somehow).

#### Steps to reproduce the error:

Try to:

```
console.log(`${someInstanceOfSomeLibp2pPublicStruct}`)
```

**Comment by GlenDC** [comment]
e.g. things like the status of a connection: https://github.com/libp2p/test-plans/blob/4443a19fdbf39b18510651ba2fe34dd42fc1db6a/ping/js/src/ping.js#L74

**Comment by achingbrain** [comment]
Thanks for sharing a link to your implementation.

I don't think the [nodejs.util.inspect.custom](https://nodejs.org/api/util.html#utilinspectcustom) solution will help here as you are coercing the js object to a string.  You get the opaque `'[object Object]'` string because lol javascript.

Instead I think you may wish to expand the functionality of the `recordMessage` function to accept a strings with sprintf style formatters - there are [plenty of modules on npm](https://www.npmjs.com/search?q=sprintf) that can be used to do it.

**Comment by p-shahi** [comment]
Going to close this issue, feel free to repoen
