### ISSUE TITLE
Update @libp2p/interface-connection

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p#1683]
The latest `@libp2p/tcp` (v6.2.0) isn't compatible with the latest `libp2p` (v0.43.4), seemingly because `@libp2p/interface-connection` needs to be upgraded throughout the ecosystem to v4.0.0.

**Comment by achingbrain** [comment]
libp2p 0.44 shipped which should restore balance to the force but agree we need a better way of managing this.

The logical place to put these things is libp2p, but the core objection here is not having components depend on lib2p directly because it creates a circular dependency.

Maybe after #1563 we could split all the components/interop/examples out into a monorepo setup that would remove the dependencies on tcp etc from libp20 and make the libp2p module itself so thin that it wouldn’t be a big deal?

Not 100% sure, might need some experimentation and thought.

**Comment by achingbrain** [comment]
Will be fixed by #824
