### ISSUE TITLE
Stream limits and relayed connections

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#1695]
Need investigation but stream limits may be being applied per-connection over relayed connections - this should be treated as a special case and applied per-relayed peer.

That is, if we have connections to 10 peers on the same relay, we’ll only have on connection so in this case stream limits should be per-peer, not per-connection.

This may be why the stream limits had to be set to high for the universal connectivity demo.

**Comment by achingbrain** [comment]
On further investigation I don't think this is what's happening.

The upgrader is the component that enforces stream limits, and relayed streams are turned into [MultiaddrConnections by the relay transport](https://github.com/libp2p/js-libp2p/blob/master/src/circuit-relay/transport/index.ts#L231-L238) which the upgrader turns into a Connection which has a separate stream count.

**Comment by joeltg** [comment]
@achingbrain any idea what else might be going on here? I'm also getting lots of unexpected `Too many outbound protocol streams for protocol "/libp2p/circuit/relay/0.2.0/hop"` errors in the logs and don't know where to look.

**Comment by p-shahi** [comment]
@joeltg dropping a note here as I saw the same stream outbound/inbound limit error wrt relay hop in an app I was helping build.
The only configurable stream limits related to circuit relay I found were:
```
    relay: circuitRelayServer({
        maxInboundHopStreams: 1000,
        maxOutboundHopStreams: 1000
    }),
```
But those are fore the relay server.
I set here: https://github.com/libp2p/universal-connectivity/pull/53/commits/3fe2dd467539443ebaeb3759569901a849cfa736 but eventually reverted

The underlying issue I saw was this:
```
libp2p:circuit-relay:transport:error Circuit relay dial failed +0ms CodeError: failed to connect via relay with status RESOURCE_LIMIT_EXCEEDED
```
This occurred b/c the rust v2 relay the app used was rejecting connections. Fixed by this: https://github.com/libp2p/universal-connectivity/pull/54
