### ISSUE TITLE
Node and npm versions in package.json

### ISSUE THREAD

**Issue by zeroxbt** [libp2p/js-libp2p#1745]
- **Version**: 0.44

- **Platform**:

- **Subsystem**:

#### Description:

When installing dependencies with node v16 as specified in package.json, the warning:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'semantic-release@20.1.3',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.1', npm: '8.11.0' }
npm WARN EBADENGINE }
```

is printed in the console as one of the dependencies requires node v18.

Shouldn't "engines" be updated in package.json ?

#### Steps to reproduce the error:

npm install using nodejs v16

**Comment by maschad** [comment]
Thanks for raising this, it seems to be related to a [transitive dependency](https://github.com/ipfs/aegir/blob/master/package.json#L228-L233) that we use for automating our releases through [project management tool](https://github.com/ipfs/aegir), perhaps we should update it there since `aegir` is a _devDependency_ Would you care to open a PR?

**Comment by zeroxbt** [comment]
Hi @maschad , thanks for the reply. It looks like this is already being worked on.

https://github.com/ipfs/aegir/tree/fix/min-node-version

**Comment by zeroxbt** [comment]
Closing as it was fixed by [this PR](https://github.com/ipfs/aegir/pull/1184).
