### ISSUE TITLE
Multidim Interop tests are broken in master

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#1809]
[This PR](https://github.com/libp2p/js-libp2p/pull/1788) was merged with green CI but now these tests fail in master.

It looks like master runs more test variations there than there were on the PR:

Master:

<img width="1045" alt="image" src="https://github.com/libp2p/js-libp2p/assets/665810/8fa7a59e-493f-4a80-ae60-04d04c10cd07">

https://github.com/libp2p/js-libp2p/actions/runs/5251996577

#1788:

<img width="705" alt="image" src="https://github.com/libp2p/js-libp2p/assets/665810/1a76caa1-9861-40b6-a56f-a96dab121925">

https://github.com/libp2p/js-libp2p/actions/runs/5201404450

CC @MarcoPolo @maschad

**Comment by maschad** [comment]
> It looks like master runs more test variations there than there were on the PR:

I believe that's because the [workflow file](https://github.com/libp2p/js-libp2p/blob/master/.github/workflows/interop-test.yml#L32) is going to run the tests against the latest JS versions in [test plans](https://github.com/libp2p/test-plans/tree/master/multidim-interop/impl/js/v0.45) but @MarcoPolo can confirm this. Regardless, I don't running those variations is a drawback as that provides better coverage. 

It seems like https://github.com/libp2p/js-libp2p/pull/1804 introduced some [inconsistency in the master CI runs](https://github.com/libp2p/js-libp2p/actions/runs/5251996577)  (given that the workflow on that PR check passed) and that previous runs tested against this [webrtc and webrtc-direct matrix were passing](https://github.com/libp2p/js-libp2p/actions/runs/5226259463) prior to this PR being merged on master, and subsequent runs post-merge of #1804 are failing.

**Comment by maschad** [comment]
> Hmm, interesting. The multidim tests [passed for the #1804 PR](https://github.com/libp2p/js-libp2p/actions/runs/5240355729) though so that might be a red herring?

Yah that's what I was referring to by stating _(given that the workflow on that PR check passed)_  but I don't think it's a red herring because all subsequent master CI Multidim interop runs have failed post-merge of #1804 so that seems to be consistent. The error also seems to be the same in that the [streams are aborting early](https://github.com/libp2p/js-libp2p/actions/runs/5251996577/jobs/9490731750#step:7:1189) (there is also [another error](https://github.com/libp2p/js-libp2p/actions/runs/5277824808/jobs/9546343035#step:7:30067) related to monorepo refactor but seems that will be fixed by https://github.com/libp2p/js-libp2p/pull/1828) 

But these tests pass locally when I run them, perhaps it's a [timeout issue](https://github.com/libp2p/js-libp2p/pull/1804/files#diff-e35b8fdd1adba91c51baebc75f04020f937dc6b20534862d0bc430a83f1af9b0R82) ?

**Comment by MarcoPolo** [comment]
The extra tests that happened in master are because I merged this PR on test-plans https://github.com/libp2p/test-plans/pull/189 that introduced js-libp2p v0.45 to the test-plans repo so that every implementation (including js-libp2p) tests against this released version of js-libp2p. https://github.com/libp2p/js-libp2p/pull/1788 Was merged before https://github.com/libp2p/test-plans/pull/189 was, so it didn't know about that released version yet.

The timelime:
* https://github.com/libp2p/js-libp2p/pull/1788 was merged. Adds webrtc and webrtc-direct interop tests.
* https://github.com/libp2p/test-plans/pull/189 was merged. Adds js-libp2p v0.45 to test-plans so every libp2p implementation tests against it.
* js-libp2p master runs use the latest test-plans commit when running tests so they are testing against js-libp2p v0.45. These are the "more test variations".

**Comment by MarcoPolo** [comment]
I wonder if the test passed in #1804 because dependency resolution worked out then, but failed after because of a different dependency resolution (just a guess). I'm going to try running the multidim CI for 1804 and see if it still passes.

**Comment by achingbrain** [comment]
If I'm reading this correctly that means the tests that are run are controlled by whatever is in master of https://github.com/libp2p/test-plans?

Is there a way to depend on a specific version of the multidim tests instead?  Otherwise commits in an unrelated repo can break CI in this repo which makes the build non-deterministic and leads to confusion like above.

Previously this was handled by having releases of https://github.com/libp2p/interop with semver and all that.

**Comment by achingbrain** [comment]
Ah, wait - we can control that [here](https://github.com/libp2p/js-libp2p/blob/master/.github/workflows/interop-test.yml#L29).

**Comment by p-shahi** [comment]
@achingbrain 
It looks like all of the interop tests are now failing as a result of failing to import modules post the monorepo consolidation: https://github.com/libp2p/js-libp2p/actions/runs/5315540166/jobs/9624024987
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@libp2p/crypto' imported from /app/packages/libp2p/dist/src/libp2p.js\n" +
```

**Comment by achingbrain** [comment]
#1842 fixes that particular error but the tests still fail so there's more work to do.

One error I'm seeing in the logs right now are:

```
unexpected exception in ping test: Error: The operation was aborted
```

This seems like a timeout to me.  @maschad has had success running these tests locally so this could be the test suite overwhelming the weaker CI machines.

The other is:

```
unexpected exception in ping test: Error: stream ended before 1 bytes became available
```

This happens when the remote closes the stream before it sends any data (e.g. before multistream select has a chance to run).  It's symptomatic of the issue described [here](https://github.com/libp2p/js-libp2p/issues/1793) and is probably related to the above.

**Comment by MarcoPolo** [comment]
WebRTC tests seem flaky to me. I don't think this is a resource issue in CI. Running these tests locally also sometimes fail for me.

Let's remove the webrtc tests for now, and add them back in when they're not flaky.
