### ISSUE TITLE
Example codes do not work

### ISSUE THREAD

**Issue by HoseinHaqiqian** [libp2p/js-libp2p#1820]
- **Version**: 0.45.6
- **Platform**: Mac os M1
- **Node version**: v19.6.0
- **Npm version**: 9.4.0

#### Description:
- What you did : 

- [x]  i executed one of the example codes with `node 1.js` command

- What happened : 

it failed with following error : `Cannot find module ..../llibp2p/dist/src/index.js improted from ..../js-libp2p/examples/peer-and-content-routing/1.js` 

- What you expected to happen : 

run successfully

**Comment by HoseinHaqiqian** [comment]
After creating project with latest version of libp2p, it gives me following error :
`Command : ts-node --esm index.ts`  

`Error : No "exports" main defined in project_path/node_modules/libp2p/package.json`

**Comment by greenSnot** [comment]
dht from the example should be moved to `peerRouters: [kadDHT()]`?
```
const node = await createLibp2p({
    addresses: {
      listen: ['/ip4/0.0.0.0/tcp/0']
    },
    transports: [tcp()],
    streamMuxers: [yamux(), mplex()],
    connectionEncryption: [noise()],
    dht: kadDHT()
  })
```

**Comment by achingbrain** [comment]
There are a few different issues here.

> it failed with following error : Cannot find module ..../llibp2p/dist/src/index.js improted from ..../js-libp2p/examples/peer-and-content-routing/1.js

This is because you need to build the monorepo first.

```console
$ git clone https://....
$ cd libp2p
$ npm i && npm run build
$ cd example/foo
$ node 1.js
```

> After creating project with latest version of libp2p, it gives me following error :
> Command : ts-node --esm index.ts
>
> Error : No "exports" main defined in project_path/node_modules/libp2p/package.json

Please see discussion in https://github.com/libp2p/js-libp2p/issues/1583 but the TLDR is that [ts-node doesn't support ESM](https://github.com/TypeStrong/ts-node/issues/1007) yet.

> dht from the example should be moved to peerRouters: [kadDHT()]?

No, the KAD-DHT implementation should be in the [services map](https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.44-v0.45.md#services), though it's unrelated to the above issues..

**Comment by HoseinHaqiqian** [comment]
Thanks.
