### ISSUE TITLE
Making connections between more than 2 peer

### ISSUE THREAD

**Issue by garyteofanus** [libp2p/js-libp2p#1834]
The current `browser-to-browser` example can only create WebRTC connection between 2 peer. If I tries to connect a new peer to an old peer that already has a connection, the old peer will change connection with the new one and abandon the old one. 

For example, imagine there are 3 peers: Peer A, Peer B, and Peer C. Peer A is already connected to Peer B and can exchange message. If Peer C connects to Peer A, Peer A will sever connection with Peer B and make connection with Peer C instead. 

Are there any plan to support connection between more than 2 peers? Or is this actually already possible but I'm missing something?

**Comment by maschad** [comment]
Hi @garyteofanus I was unable to reproduce this issue in the repo. There have been some updates to [webRTC as well as libp2p](https://github.com/libp2p/js-libp2p/blob/master/packages/libp2p/CHANGELOG.md#L2-L3) since then as well. If you are able to reproduce this could you re-open an issue using our [issue template](https://github.com/libp2p/js-libp2p/blob/master/.github/ISSUE_TEMPLATE/open_an_issue.md) ?
