### ISSUE TITLE
ambient peer discovery in the browser

### ISSUE THREAD

**Issue by tabcat** [libp2p/js-libp2p#1865]
- **Version**: libp2p@0.45.9

- **Platform**: Linux joemama 5.19.0-45-generic # 46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 x86_64 x86_64 x86_64 GNU/Linux
- **Browser**: Brave (Chromium)

- **Subsystem**: Relay, Pubsub

#### Description:
Clients are not discovering each other passively. After connecting them manually and subscribing to the same pubsub topic; peers become pubsub peers but never add each other to the topic mesh.

#### Steps to reproduce the error:
https://github.com/tabcat/libp2p-pubsub

**Comment by tabcat** [comment]
Getting an error when calling pubsub.publish

```
Uncaught TypeError: Cannot read properties of undefined (reading 'Message')
    at buildRawMessage (buildRawMessage.ts:43:1)
    at GossipSub.publish (index.ts:2050:1)
    at <anonymous>:1:30
```

Looks like RPC is undefined.

https://github.com/ChainSafe/js-libp2p-gossipsub/blob/89c82f6c06ee29e0b7c84ef4165ba38ff672394c/src/utils/buildRawMessage.ts#L40

Probably due to bundler?

**Comment by bradwbradw** [comment]
I was trying to get browser peers to discover eachother for a really long time during the last hackFS, never was successful. Seeing this issue pop up makes me feel less like I was shooting myself in the foot, so thank you.

I forked your repro and added some simple GUI:  https://github.com/bradwbradw/libp2p-pubsub

In my repro, I have two client instances in the same browser window. Each shows two lists: 1) The peers in the peerStore (`libp2p.getPeers()`) and 2) A list that's appended whenever `peer:discovery` occurs. Each client instance also waits for `self:peer:update` and updates the "self" label accordingly.

There was inconsistent behaviour in between refreshes of the browse window. Sometimes, I see scenario A, and sometimes (much less frequently) I see scenario B. Now lately since writing this, I see scenario C.

Scenario A: Nothing under "self" (no self:peer:update is observed). The relay node is the only peer in the peerStore list. In the discovered peers list, there is a single ID (it's not the relay node)

![Screen Shot 2023-07-04 at 10 36 00 PM](https://github.com/libp2p/js-libp2p/assets/4715252/061d86b4-e548-4f64-8f4e-7ed9fe6a2340)

Scenario B: Self shows an ID, that's also seen in the other peer's lists. It would appear like discovery is behaving as expected in this scenario. But I have no idea why there are so many peers
![Screen Shot 2023-07-04 at 10 30 33 PM](https://github.com/libp2p/js-libp2p/assets/4715252/f5b5cb9a-2a4c-46ca-b912-8e9abd0b3355)

Whenever Scenario B happens, after about 10 seconds, there is a bunch of instances of an uncaught runtime error:

![Screen Shot 2023-07-04 at 10 30 18 PM](https://github.com/libp2p/js-libp2p/assets/4715252/2cc2ee5f-e7b9-458a-b476-7cfb3e91fe09)
![Screen Shot 2023-07-04 at 10 32 11 PM](https://github.com/libp2p/js-libp2p/assets/4715252/0ff656c4-9527-44f2-ba2a-44832e3e218c)

Scenario C: nothing in Self, nothing in peerStore, only one discovered peer.

Since writing this, I turned off React Strict mode, and this has led to more consistently C all the time.

What I would expect is to see 3 peers in both the peersStore list and Discovered peers list. one for the blue-bordered client, one for the green-bordered client, and one for the relay node.

**Comment by tabcat** [comment]
Working fine for me now, must have been doing something wrong.

**Comment by maschad** [comment]
Thanks for following up @tabcat :) 

@bradwbradw I took a look at your [peer discovery config](https://github.com/bradwbradw/libp2p-pubsub/blob/master/relay.js#L34) and I noted that you're using _gossipsub_ but with no configuration, to avoid going into the complexities of _gossipsub_, have you tried seeing if you are able to discover peers using [a bootstrap node](https://github.com/libp2p/js-libp2p/tree/5eee70a4b83e05342c629dda41a0b59b43ce30a3/examples/discovery-mechanisms#1-bootstrap-list-of-peers-when-booting-a-node) and then connect that way? You can take a look at [this example](https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser) as a starting point, but I think the issue @tabcat raised is unrelated to what you are trying to solve.

If you are still having problems after trying that, feel free to open an new issue using our [issue template](https://github.com/libp2p/js-libp2p/blob/master/.github/ISSUE_TEMPLATE/open_an_issue.md)

**Comment by bradwbradw** [comment]
@tabcat are you able to share what you were doing wrong or what you discovered?

Thanks @maschad I will take another look and open a new issue if need be

**Comment by tabcat** [comment]
The advertise option seemed to help @bradwbradw 

```
    circuitRelayServer: circuitRelayServer({
      advertise: { bootDelay: 10 }
    })
```

**Comment by tabcat** [comment]
@bradwbradw turning on debug logs for circuit-relay helped
