### ISSUE TITLE
Bootstrap multiaddrs not added to peerstore

### ISSUE THREAD

**Issue by sneaker1** [libp2p/js-libp2p#1871]
- **Version**:
"libp2p": "^0.45.9",
"@libp2p/bootstrap": "^8.0.0",

- **Platform**:
Linux, Browser

- **Subsystem**:
Bootstrap

#### Description:
I am starting a local libp2p node with a bootstrap list with a dns multiaddress
```
bootstrap({
  list: [
    "/dns4/MY-DOMAIN/tcp/443/wss/p2p/QmTj1DC9d4PfB4iSA52yH5iCcqsYgUPz2xqGvbym9NazZ9"
  ]
})
```

When starting the local node the connection to the bootstrap peer is established as expected.

When I look at the peerstore though, the multiaddress from the bootstrap list is not included there. The peerstore only contains some local addresses of the bootstrap peer. (The bootstrap peer is running in a docker container with reverse proxy on a public server and has no announce address set)

If the connection to the bootstrap peer is disconnected, the connection manager won't reconnect to the bootstrap peer. Probably because the peerstore doesn't contain a dialable address to the bootstrap node.

My expectation would be that the local node adds the multiaddresses which it learned from the bootstrap list directly to the peerstore.

**Comment by maschad** [comment]
The default TTL for a bootstrap node is [two minutes](https://github.com/libp2p/js-libp2p/blob/daeb43d8821d2df1999871797a22fbdf502731f8/packages/peer-discovery-bootstrap/src/index.ts#L16), which means the nodes connections may be closed if the maximum number of connections is reached. Clients that need constant connections to bootstrap nodes can set the [TTL to Infinity](https://github.com/libp2p/js-libp2p/blob/daeb43d8821d2df1999871797a22fbdf502731f8/packages/peer-discovery-bootstrap/src/index.ts#L43).

**Comment by sneaker1** [comment]
I tried to set the ttl value, as you proposed, but that didn't work for my scenario.

I try to explain the scenario more clearly:

1. Local Node starts and connects to the bootstrap node as expected.
3. Local Node manually closes the connection to the bootstrap node. (only connection)
4. Local Node wants to connect to the bootstrap node again via `dial(bootstrap node id)`

Step 3 fails because the in the peerstore for the bootstrap peer only some invalid local addresses are saved because the bootstrap peer hasn't set a announce address and is inside a docker container.

What I want is that the local node saves the valid bootstrap node address in its peerstore as soon as it learns it from the configuration on startup.

**Comment by maschad** [comment]
Thanks for clarifying. Unfortunately if there isn't an `announceAddress` configured then that address won't be added to our peer record when the address manager is [updating our observed addresses](https://github.com/libp2p/js-libp2p/blob/57c32721c881aeb39979be0604c379c47bda8374/packages/libp2p/src/address-manager/index.ts#L114-L130)

You could manually [populate the address book](https://github.com/libp2p/js-libp2p/blob/57c32721c881aeb39979be0604c379c47bda8374/packages/libp2p/test/fixtures/creators/peer.ts#L61-L71) with that specific node address when the [connection closes](https://github.com/libp2p/js-libp2p/blob/57c32721c881aeb39979be0604c379c47bda8374/packages/interface/src/index.ts#L227) as an alternative but because [observed addresses](https://github.com/libp2p/js-libp2p/blob/57c32721c881aeb39979be0604c379c47bda8374/packages/libp2p/src/address-manager/index.ts#L155C3-L155C19) may change over time on a network then it's unreliable to automatically save them to the peerStore.
