### ISSUE TITLE
feat: autoDialer backoff implementation

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p#1899]
autoDialer should support configurable exponential backoff, or retry policies, for multiaddr that have consistently failed to establish a connection:

related to 
* https://github.com/libp2p/js-libp2p/issues/744#issuecomment-1650555616
* https://github.com/libp2p/js-libp2p/issues/1897
* https://github.com/libp2p/js-libp2p/issues/1898

**Comment by maschad** [comment]
Discussion from Open Maintainers call on 1/08/2023

Potential solution:

Penalize peers / multiaddrs via decreasing their [tag value](https://github.com/libp2p/js-libp2p/blob/b3c87b6dc14192ad4fe24b51738b4867a2177d1d/packages/interface/src/peer-store/index.ts#L116-L121) if dials are [failing / rejected dials](https://github.com/libp2p/js-libp2p/blob/b3c87b6dc14192ad4fe24b51738b4867a2177d1d/packages/libp2p/src/connection-manager/dial-queue.ts#L500) so that they are [moved lower in the dial-queue](https://github.com/libp2p/js-libp2p/blob/b3c87b6dc14192ad4fe24b51738b4867a2177d1d/packages/libp2p/src/connection-manager/auto-dial.ts#L179-L209).

cc @achingbrain
