### ISSUE TITLE
bug: missing support for `/tls` multiaddr

### ISSUE THREAD

**Issue by danisharora099** [libp2p/js-libp2p#2024]
- **Version**: 0.46.x
- **Platform**: macos
- **Subsystem**: Dialer

#### Description:
js-libp2p throws an error `Unsupported protocol tsl` when a multiaddr `/ip4/192.168.68.58/tcp/433/tls/ws/p2p/16Uiu2HAkyZuLQy4sPRte7khemYHmkQewzjdTPRXZcxPH6NgjhR97` is dialed

The expectation is that a secure websocket multiaddr would have `/wss/` but apparently `wss` was replaced by `/tls/ws`:
- https://github.com/multiformats/go-multiaddr/pull/153
- https://github.com/multiformats/multiaddr/pull/109
- https://github.com/multiformats/multiaddr/issues/163

#### Steps to reproduce the error:
Try to dial `/ip4/192.168.68.58/tcp/433/tls/ws/p2p/16Uiu2HAkyZuLQy4sPRte7khemYHmkQewzjdTPRXZcxPH6NgjhR97` through js-libp2p

**Comment by maschad** [comment]
Could you share the example where you tried to dial this address? as well as the dependencies of the listening node and the environment? 

You are correct in that `wss` was deprecated although we still utilize it internally in our monorepo tests,

but it's strange that you get this error since there's support for backwards compatibility that is [tested in multiaddrs](https://github.com/multiformats/js-multiaddr/blob/469082623892e1d801951596902573675a27c8cb/test/index.spec.ts#L427-L432)

I have tried to dial the multiaddr you shared  but I am getting a timeout error ( I assume the node isn't running at that public IP at the moment).

But I am able to have two local nodes dial each other with the current format as such:

```javascript

import { createLibp2p } from 'libp2p'
import { webSockets } from '@libp2p/websockets'
import { mplex } from '@libp2p/mplex'
import { noise } from '@chainsafe/libp2p-noise'
import { yamux } from '@chainsafe/libp2p-yamux'
import { tcp } from '@libp2p/tcp'
import { identifyService } from 'libp2p/identify'

const node1 = await createLibp2p({
   addresses: {
    listen: ['/ip4/127.0.0.1/tcp/8000/tls/ws']
  },
  transports: [
    tcp(),
    webSockets()
  ],
  streamMuxers: [yamux(), mplex()],
  connectionEncryption: [noise()],
  services: {
    identify: identifyService()
  }
})

const node2 = await createLibp2p({
   addresses: {
    listen: ['/ip4/127.0.0.1/tcp/8001/tls/ws']
  },
  transports: [
    tcp(),
    webSockets()
  ],
  streamMuxers: [yamux(), mplex()],
  connectionEncryption: [noise()],
  services: {
    identify: identifyService()
  }
})

await node1.start()
await node2.start()

const connection = await node1.dial(node2.getMultiaddrs()[0])

console.log('node1 is connected to node2:', connection.status)
// Status is logged as open
```

**Comment by achingbrain** [comment]
Could you also confirm the version of `@multiformats/multiaddr` you have installed?  `/tls` support was only [added](https://github.com/multiformats/js-multiaddr/pull/306) in `11.4.0` - 

```console
$ npm ls @multiformats/multiaddr
```

**Comment by maschad** [comment]
Closing as https://github.com/libp2p/js-libp2p/pull/2059#issuecomment-1724031879 should solve the issue
