### ISSUE TITLE
Linting support in vscode

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p#2095]
- **Version**:
latest master

- **Platform**:
linux

- **Subsystem**:
IDE support

#### Severity:
?

#### Description:
My linter is not properly configured, so I can't see linter errors in vscode.
Does anyone else have it working? Are there any specific steps I need to get it working?

#### Steps to reproduce the error:

- Open root js-libp2p directory in vscode
- Open a typescript file, see this:
![Screenshot from 2023-09-30 15-04-08](https://github.com/libp2p/js-libp2p/assets/1348242/6d0e1a4d-9476-4236-a974-74fbdf61d059)

**Comment by SgtPooki** [comment]
@wemeetagain it works well for me only when I open the individual packages in vscode. If I open the repositories root in vscode, linting also fails for me

**Comment by wemeetagain** [comment]
\*cries in devex*

**Comment by wemeetagain** [comment]
@SgtPooki #2109 seems to work for me, can you test locally and see if it works for you?

**Comment by achingbrain** [comment]
Is this new? I’ve never had this problem in vacode.

**Comment by maschad** [comment]
I had this issue as well when opening at the monorepo level, and it was solved by #2109 🤷🏾

**Comment by achingbrain** [comment]
Right, so - it's caused by the eslint vscode plugin which I didn't have installed which is why I haven't seen this error.

The fix in #2109 has some problems outlined [here](https://github.com/libp2p/js-libp2p/pull/2109#issuecomment-1746674817) - there's a (I think) better fix here: https://github.com/libp2p/js-libp2p/pull/2122
