### ISSUE TITLE
`metadata.get()` returns `<Buffer>` instead of `Uint8Array`

### ISSUE THREAD

**Issue by danisharora099** [libp2p/js-libp2p#2146]
- **Version**: 0.46

- **Platform**: macos 
 
- **Subsystem**: Peer/PeerStore

#### Description:
When trying to set `metadata` with a `Uint8Array` as the value, and then later `get()` it, the returned value is actually a `<Buffer>` instead of the expected `Uint8Array` that comes from the types

Not sure if this how `metadata` in specific is handling this, or if this is a generic typescript-node related bug (not much info on stackoverflow/docs either) but I wasn't able to reproduce this in native node:

![image](https://github.com/libp2p/js-libp2p/assets/35004822/455cdc43-3472-4154-b1f1-ffc46f6c701f)

#### Steps to reproduce the error:
```
const uarr = new Uint8Array([1, 2, 3, 4]);
      console.log({ setting: uarr });

      // update the tags for the peer
      await this.components.peerStore.save(peerId, {
        ...{
          metadata: {
            shardInfo: uarr
          }
        }
      });

      console.log({
        getting: (await this.components.peerStore.get(peerId)).metadata.get(
          "shardInfo"
        )
      });
```

Logs:
```
starting test
{ setting: Uint8Array(4) [ 1, 2, 3, 4 ] }
{ getting: <Buffer 01 02 03 04> }
```

**Comment by maschad** [comment]
The [Buffer class](https://nodejs.org/api/buffer.html#buffer) is a subclass of the Uint8Array class and extends it with methods that cover additional use cases. What is your use case that causes this to be a bug for you?

**Comment by wemeetagain** [comment]
Curious what you are doing that is not compatible between a Buffer and Uint8Array. In the vast majority of cases, there should be no difference.

Recommend you refactor your util function to accept a Buffer and do something like so: `utilFn(metadata.get(...) as Buffer)`

**Comment by wemeetagain** [comment]
Our interfaces use `Uint8Array` to align across browser and nodejs environments. Since you're running in node, you're likely using a leveldb backend for your datastore/peerstore, which returns `Buffer`s.

I would really recommend that you don't use the the methods that are inconsistent between `Buffer` and `Uint8Array`.
If you stay away from `splice` and `toString` you should be fine. In general, you're asking for trouble when you rely on `Buffer`-specific or `Uint8Array`-specific variants of those methods on instances from code you don't control. The reason is exactly the issue you face.

A `Buffer` is a `Uint8Array` from a typechecking perspective as well as a `instanceof` perspective. So any typescript library code that accepts a `Uint8Array` also should accept a `Buffer`. And any library code that returns a `Uint8Array` may return a `Buffer`. Any code boundary that relies on `Buffer` or `Uint8Array` specific variants should explicitly convert or assert that its inputs are already converted.
