### ISSUE TITLE
Circuit Relay Transport is Disabled if 'discoverRelays' is set to zero

### ISSUE THREAD

**Issue by justin0mcateer** [libp2p/js-libp2p#2160]
- **Version**:
0.46.14

- **Platform**:
`Linux master 6.5.6-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 07 Oct 2023 08:14:55 +0000 x86_64 GNU/Linux`
`Brave Browser 117.1.58.137`

- **Subsystem**:
Circuit-Relay Transport

#### Severity:
High

#### Description:
There is logic in the Circuit Relay transport to 'discover' relays by several means. However, discovering relay addresses may not be needed. Setting 'discoverRelays' to zero disables the 'discovery' capability (via the DHT, etc). However, when discoverRelays is set to zero, the Circuit Relay Transport won't establish a Relay Reservation even when the Relay is directly dialed and connected to, making the Circuit Relay Transport effectively useless.

#### Steps to reproduce the error:
Configure circuitRelayTransport, set 'discoverRelays' to zero.
Observe that the Circuit Relay Transport Listener never creates a reservation and never advertises a listen address via the Relay.

**Comment by achingbrain** [comment]
> when discoverRelays is set to zero, the Circuit Relay Transport won't establish a Relay Reservation even when the Relay is directly dialed and connected to, making the Circuit Relay Transport effectively useless

If you have a specific relay you wish to establish a reservation on, you should configure it as a listen address - see https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md#setup-with-preconfigured-reservations

Otherwise setting `discoverRelays` to a positive number will search the network for a relay to use - see https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md#setup-with-automatic-reservations
