### ISSUE TITLE
logger: please export createDisabledLogger

### ISSUE THREAD

**Issue by paralin** [libp2p/js-libp2p#2276]
The function to create a disabled logger is not exported:

https://github.com/libp2p/js-libp2p/blob/bca8d6e689b47d85dda74082ed72e671139391de/packages/logger/src/index.ts#L86

Please export some way of constructing a no-op Logger and ComponentLogger.

**Comment by achingbrain** [comment]
Where you need a `ComponentLogger` you can just use `defaultLogger`?  Otherwise if you need a `Logger` just use the regular `logger` export?

Logging will be disabled if the `DEBUG` env var is not present.

**Comment by achingbrain** [comment]
The modules in question require a `ComponentLogger`, `createDisabledLogger` returns a `debug.Debugger` which is not the same thing so this isn't going to solve the problem you face.

**Comment by paralin** [comment]
Okay, can we export a disabled ComponentLogger then?...

**Comment by paralin** [comment]
@achingbrain it doesn't make me excited to work with libp2p when even basic requests are closed without resolution. I love the project and have built things on top of it and plan to contribute more. But I don't feel that the style of trying to close things as fast as possible is conducive to progress.

**Comment by achingbrain** [comment]
I'm sorry that you feel this way, the reason I closed this issue is detailed above.

To reiterate:

Your problem is, I think, you have a libp2p component that requires a libp2p `ComponentLogger`.

The suggestion is to export something which can be passed to the component to satisfy the requirement for a logger and for it to not do anything.

The resolution here is:

1. Exporting `createDisabledLogger` will not work because it returns the wrong type.  Instead, you should use the existing `defaultLogger` from `@libp2p/logger` which is of the correct type.
2. There's no need to export a "disabled ComponentLogger" because logging is disabled by default, so it's redundant - if you use `defaultLogger` as suggested, you will have a `ComponentLogger` that satisfies the API, and it'll be disabled.

I hope that clears things up.

There may be broader questions here like "should all libp2p components require a logger" and "should I be able to use libp2p components outside of libp2p" but these may be better off as [discussions](https://github.com/libp2p/js-libp2p/discussions).

**Comment by paralin** [comment]
I don't see any reason to not have a no-op logger, and it would be 10 lines of code to export one.

**Comment by achingbrain** [comment]
Unless you turn logging on, `defaultLogger` is a no-op logger so there's no need to export anything else.

**Comment by paralin** [comment]
I understand. And I see your position on this. But I don't want to even have it behind a DEBUG environment variable, rather would prefer to just stub it.

I appreciate your responses and will just write a no-op logger out of tree. Thanks for taking the time to reply.
