### ISSUE TITLE
Splitted Data When Transmission Data Length Exceeding Send Window Limitation

### ISSUE THREAD

**Issue by frystal** [libp2p/js-libp2p#2359]
## Version: 
"devDependencies": {
    "aegir": "^41.0.2"
  },
## Platform: 
Ubuntu20.04
## Subsystem: 
yamux
## Severity: 
Low
## Description:
When i am using the [sendData function](https://github.com/ChainSafe/js-libp2p-yamux/blob/master/src/stream.ts#L94)  of js-libp2p-yamux in JS-libp2p, there's an issue where if the data to be sent exceeds the send window limit, only the send window amount is transmitted, leaving the rest unsent. 

However, in the [js-libp2p](https://github.com/libp2p/js-libp2p/blob/master/packages/multistream-select/src/handle.ts#L65),  it does not verify if the entire data has been received. If the full length of the data is not sent, it will report an error.

For instance, if we set the send window to 100 and disable processing receive window updates, the remote peer will receive fragmented identity data and handle it incorrectly.
![image](https://github.com/ChainSafe/js-libp2p-yamux/assets/44425340/b08cbeca-a216-4833-bec2-d44ab59e5105)

In my opinion, it should send the entire data as a single package rather than splitting it into two and waiting for the remaining data to send.

Might it be the cause?

I suspect it is caused by the behavior of the [stream-muxer](https://github.com/libp2p/js-libp2p/blob/master/packages/interface/src/stream-muxer/stream.ts#L179) in the js-libp2p. It continues to send data to the function 'sendData' without waiting for the previous 'sendData' operation to finish. This leads to the situation depicted in the diagram below.

When the first protocol negotiation is completed, if the protocol attempts to send a message (specifically, the Identify Message) larger than the current send window limitation, it will first send the initial 'n' bytes allowed by the send window. Subsequently, the rest message (EOF) to send via 'sendData' is continued and blocked. This behavior is due to the non-blocking nature of the stream-muxer.

When the Responder responds with the windows update message for the protocol negotiation, all the previously blocked 'sendData' operations start to execute. However, the 'EOF' is sent before the remaining part of the 'Identify Message,' resulting in message disorder for the protocol.
![image](https://github.com/ChainSafe/js-libp2p-yamux/assets/44425340/ffb25e57-2994-4b1b-b89a-c15b3f4608e1)
![image](https://github.com/ChainSafe/js-libp2p-yamux/assets/44425340/75fa8a8b-ce69-4fa7-b469-3337c329fd03)

## Steps to reproduce the error: None

**Comment by achingbrain** [comment]
> When i am using the [sendData function](https://github.com/ChainSafe/js-libp2p-yamux/blob/master/src/stream.ts?rgh-link-date=2024-01-14T15%3A15%3A57Z#L94) of js-libp2p-yamux in JS-libp2p, there's an issue where if the data to be sent exceeds the send window limit, only the send window amount is transmitted, leaving the rest unsent.

This is by design and how backpressure works in Yamux.  If the data to be sent exceeds the window limit, the sender should [wait for the remote to increase the limit](https://github.com/ChainSafe/js-libp2p-yamux/blob/master/src/stream.ts#L101).  This lets the remote signal that it's ready to receive more data.

> For instance, if we set the send window to 100 and disable processing receive window updates

If you disable processing window updates you'll not know when it's ok to send more data so things won't work as expected.

> In my opinion, it should send the entire data as a single package rather than splitting it into two and waiting for the remaining data to send

If you ignore the send window size, the remote would be within it's rights to close the connection since you aren't following the protocol any more.

> I suspect it is caused by the behavior of the [stream-muxer](https://github.com/libp2p/js-libp2p/blob/master/packages/interface/src/stream-muxer/stream.ts?rgh-link-date=2024-01-14T15%3A15%3A57Z#L179) in the js-libp2p. It continues to send data to the function 'sendData' without waiting for the previous 'sendData' operation to finish.

Are you sure this is true?  The `AbstractStream` superclass [awaits on any promise returned from sendData](https://github.com/libp2p/js-libp2p/blob/main/packages/utils/src/abstract-stream.ts#L184).

If you're seeing something different can you please open a PR with a failing test case that demonstrates the problem?
