### ISSUE TITLE
Ping recording connection latency/aliveness

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#2643]
If the user has configured the ping protocol, we could have it periodically check that the remote is still available.  It could store the ping time as a 'latency' or 'rtt' property on the `Connection` object.

If it fails, the connection should be closed.

This is similar to https://github.com/alanshaw/it-ws/issues/113 or https://github.com/ChainSafe/js-libp2p-yamux/issues/76 except it would work across all transports and muxers, including those transports with their own muxers.

This would be non-breaking so can go in independently of 2.0.0.

**Comment by dhuseby** [comment]
@achingbrain, @lukax from Piñata was seeing an issue with js-libp2p peers getting stuck when his peer gets shutdown due to resource limits when running in a lightweight worker execution context. I *think* the fix for this issue will make js-libp2p peers more responsive to detecting when the remote peer disappears. Is that correct?

There's another aspect of this he's exploring which is: would it be possible to signal to remote peers that if they detect a connection drop that they should immediately redial? In is case, when the resource limit is hit, his peer gets instantaneously rebooted. So if the remote peers knew to re-dial immediately, then the reboot would have minimal consequences.

**Comment by achingbrain** [comment]
> an issue with js-libp2p peers getting stuck

Could you go into a bit more detail of what this means?  Perhaps @lukax could open an issue?

>  I think the fix for this issue will make js-libp2p peers more responsive to detecting when the remote peer disappears

Yes, with the caveat that the problem it fixes has primarily been observed in WebSocket connections, though that's not to say it doesn't exist elsewhere.

> would it be possible to signal to remote peers that if they detect a connection drop that they should immediately redial?

I don't think this is a good idea.  If I spun up a few hundred peers, dial you and tell you to redial on disconnect, then shut them down, you'd swamp your dial queue trying to dial 100s of non-existent peers which could effectively take you offline or at least limit your connectivity until the dial queue empties.

If a node has peers it classes as "high value", for example they are in the root KAD bucket or in a GossipSub mesh for a topic that is important or something else, they should tag the peer with `KEEP_ALIVE`.

The important difference is it's up to the node to decide which peers are important, you cannot tell it to treat a peer as such.
