### ISSUE TITLE
Now that pnet is part of js-libp2p, the docs need to be updated

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#452]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/1211152/64536634-19666300-d322-11e9-8764-2d85e44bc180.png">

**Comment by georgeaf99** [comment]
I'll throw this in as well: the "Private Networks with IPFS" example link on https://github.com/libp2p/js-libp2p/blob/master/src/pnet/README.md is broken.

Pesky broken links! ;)

**Comment by kpp** [comment]
How do I use pnet as a part of libp2p then?

**Comment by Ziwei-Wei** [comment]
> How do I use pnet as a part of libp2p then?

Same issue here. I am trying to use the module and it is not there right now.
If you npm install libp2p, you get libp2p, libp2p-crypto, libp2p-crypto-secp256k1, and libp2p-websockets in your node_modules. So the bundle example right now is obsolete.

**Comment by jacobheun** [comment]
I created a PR to fix the examples, readme's and links https://github.com/libp2p/js-libp2p/pull/464.

The major thing to note is that `libp2p-pnet` is now part of libp2p core. We will likely improve the usage during the async refactor, but right now you can use `require('libp2p/src/pnet')` instead of `require('libp2p-pnet')`. The PR includes an update to the pnet-ipfs example to also work with the latest ipfs.

**Comment by daviddias** [comment]
> but right now you can use require('libp2p/src/pnet') instead of require('libp2p-pnet')

Should it be a config value rather than an import?

**Comment by jacobheun** [comment]
> Should it be a config value rather than an import?

Potentially. I'm looking to work on this as part of the async refactor (targeting this week for pnet). It should still be modular so that people can use their own private connection module, but I think if it's enabled we can default to the provided protector.
