### ISSUE TITLE
Maintain `Packages` section up to date

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p#47]
@RichardLitt do you happen to have a tool that we can use to update the https://github.com/libp2p/js-libp2p#packages section? The ideal would be to run a script over an array of org/repo and fill and update the table putting them into their respective collection.

- Bonus1: if we can have a way to signal the status of the implementation
- Bonus2: if we can help @VictorBjelkholm use it for the Website tables

**Comment by VictorBjelkholm** [comment]
Yeah, for the libp2p.io table, all we need is to be able to format it to yml or json, so should be simple :+1:

**Comment by RichardLitt** [comment]
I do not currently have a tool that updates multiple GitHub repositories, although I've wanted to build one for a while. As I am due to greenlight the repos this quarter, now may be the time to do this. @lgierth I know you had a tool you use to hit multiple repos; is it the one currently in ipfs/devtools?

Alternatively, I could add a column to project-repos for this.

**Comment by diasdavid** [comment]
Follow on #212
