### ISSUE TITLE
DHTs and NATs

### ISSUE THREAD

**Issue by gavinmcdermott** [libp2p/js-libp2p#53]
Hey @diasdavid, 

With some of the advances we've made on Nomad, @ReidWilliams and I now have a couple specific questions regarding `libp2p` for our next steps / where we might contribute.

### Relevant Background & State

We are almost wrapped up porting Nomad over to a js-only package (the `pure-js` branch is [here](https://github.com/IDEO-coLAB/nomad/tree/feat/pure-js)). Our intent / end goal is for Nomad to run in the browser, connect to peers, receive messages and the like without reliance on anything outside of what `IPFS` / `libp2p` / `nomad` provides.

Our browser bundle builds, and as we're now looking to expose more folks to this ecosystem, one of the on-ramps is to use it as a rapid prototyping tool (been doing this already within IDEO). So to meet the goal mentioned above we're taking a couple of steps to shim the js-only module.

And this is where we have questions...

### Question: DHT

Because the DHT is not yet implemented in js-land, we are adding `dht-shim`. Basically this is a [simple server](https://github.com/IDEO-coLAB/nomad-dht-shim), store, and utils (only for use at this early stage) that take care of connecting peers.

I know the DHT has been on the roadmap and in the conversation for a while (also saw the recent question on it [here](https://github.com/libp2p/js-libp2p/issues/51)). So with the above in mind, we're curious as to:
- How far off it might be (I saw work started on the DHT [here](https://github.com/libp2p/js-libp2p-dht))?
- Is this possibly an area where contribution is needed?

### Question: Peers behind NATs

When it comes to peers behind NATs, it would be great to avoid reliance on a central signaling server (Note: the optionality of setting up your own signaling server is far better than not being able to participate). We were about to add the `webrtc-star` transport, but before we did this, we wanted to check in with you to see:

- Are there any initiatives that we've missed in the community to help with connecting peers behind NATs?
- Are there any libraries that you're aware of that might help with this? (E.g.: perhaps there's an interesting project you know of and you're awaiting someone to implement the transport)
- Is the above-mentioned goal feasible?

### Goal

Our goal is to keep moving things forward, and to continue learning by having people build :) Once we have a better understanding of the above areas, we'll get the next steps out for review!

Thanks in advance!

**Comment by diasdavid** [comment]
Hi @gavinmcdermott @ReidWilliams  o/ Good to hear back from you :)

We should definitely jump into some kind of fast communication medium (like an hangout), to catch up, there are lot of details that need to be covered, but the bulk of it is:

- Is the DHT work going to happen this Quarter? Yes, later this Quarter, see the ROADMAP at https://waffle.io/ipfs/roadmaps. Right now we are doing all of the other pieces to make that work nicely, see: https://github.com/ipfs/pm/issues/310#issuecomment-273728526
- Help is always welcome, it would be beneficial if you can tackle the issues we have at hand for each sprint, otherwise, the context switching cost will be very expensive by going back and forward on things we have deferred later in the quarter.
- NAT. Yes, there is a ton of work available for NAT Traversal, WebRTC is kind of a canon to solve this problem, but not every peer will have WebRTC neither we can trust WebRTC 100% of the times. Relay is one of the solutions, but to get a much deeper understanding I would recommend reading through:
  - https://tools.ietf.org/html/rfc5128
  - http://www.brynosaurus.com/pub/net/p2pnat/
  - https://samy.pl/chownat/
  - http://samy.pl/pwnat/
  - https://en.wikipedia.org/wiki/Universal_Plug_and_Play
  - https://www.npmjs.com/package/pmp
  - There are more modules -- https://www.npmjs.com/search?q=nat+traversal --, I haven't looked at them all. Getting a throughout review of them would be awesome.

**Comment by gavinmcdermott** [comment]
Awesome @diasdavid ! I'll ping you on IRC to follow up on these in that case—look forward to catching up!

**Comment by dignifiedquire** [comment]
hey @gavinmcdermott yes the DHT is coming later this quarter, unless @diasdavid literally ties me up somewhere ;)

**Comment by gavinmcdermott** [comment]
Thanks @dignifiedquire - I'm keen on this!

**Comment by diasdavid** [comment]
Hi @gavinmcdermott, long time no see! I hope everything is ok.

I've been revamping, polishing and cleaning a lot of stuff in libp2p land to help people get started. One of the steps is curating the issues so that they become the most objective possible. I'm breaking this one into two:

- NAT https://github.com/libp2p/js-libp2p/issues/104
- DHT https://github.com/libp2p/js-libp2p/issues/51

Please track it there and also take a peak on https://github.com/libp2p/js-libp2p/issues/95

**Comment by diasdavid** [comment]
@gavinmcdermott see my update here: https://github.com/libp2p/js-libp2p/issues/51#issuecomment-317094474 :)
