### ISSUE TITLE
no peer:connect event with autoDial

### ISSUE THREAD

**Issue by olivier-nerot** [libp2p/js-libp2p#664]
With libp2p V0.28,  peer:connect events seems not to be fired
```
const peerid = ...;
const libp2p = await Libp2p.create({
        peerId: peerid,
        addresses: {
          listen: ['/ip4/0.0.0.0/tcp/0'],
        },
        modules: {
          transport: [TCP],
          streamMuxer: [Mplex],
          peerDiscovery: [MulticastDNS],
        },
        config: {
          peerDiscovery: {
            autoDial: true,
            [MulticastDNS.tag]: { // or mdns: ?
              interval: 1000,
              enabled: true,
            },
          },
        },
      });

      libp2p.on('peer:discovery', (peerId) => {
        debug('Discovered: %O', peerId);
        // libp2p.dial(peerId);
      });

      libp2p.connectionManager.on('peer:connect', (connection) => { 
        debug('peer connected %O',connection);
      });

      libp2p.start();
```

With the same setup, if I launch `libp2p.start()` from another node, the `peer:discovery` is well logged, but not `peer:connect`. I thought the `autoDial:true` should make a peer dials other discovered peers automatically.
I've tried also to call `libp2p.dial(peerId)` into the peer:discovery event, but `peerId` has no `multiaddrs` value, and have not found how to dial a discovered peer.

The documentation is sometimes confusing with this discovery process (for example, some explains to use `mdns`, other tells to use `[MulticastDNS.tag]`in config)

**Comment by vasco-santos** [comment]
@olivier-nerot I will have a look into the docs to see where we have these inconsistencies and also add the error and docs for the required encryption.

> Dealing with this setup, to better understand, does [MulticastDNS.tag] or mdns be used ?

We aim to use `MulticastDNS.tag` to be specific on where the tags come from in the discovery modules

https://github.com/libp2p/js-libp2p-mdns/blob/master/src/index.js#L104

Its value is `mdns` and that's why it will work either way.

> And If autoDial is false, how is it possible to dial a peer on peer:discovery event, as peerid has no multiaddrs whereas dial() requires them ?

When a `peer:discovery` event happens, the discovered peer data is stored in the PeerStore [libp2p/js-libp2p/v0.28.0/src/index.js#L485-L493](https://github.com/libp2p/js-libp2p/blob/v0.28.0/src/index.js#L485-L493). `libp2p.dial` accepts a multiaddr and PeerId as a target to dial. If you provide a multiaddr, it will be used for the dial, while if you provide a PeerId, we will look into the PeerStore.AddressBook if we know any multiaddrs for the provided peer. If we do, we just try to dial using the known multiaddrs. You can read more about the PeerStore flows in [libp2p/js-libp2p/v0.28.0/src/peer-store](https://github.com/libp2p/js-libp2p/tree/v0.28.0/src/peer-store)

**Comment by olivier-nerot** [comment]
Thanks a lot. I understand it better. To help, you have `MulticastDNS.tag` in the Customizing Peer Discovery section of [Configuration.md](https://github.com/libp2p/js-libp2p/blob/72f37acd4a54bf5c3b67647d1723f556a59a43e5/doc/CONFIGURATION.md) and `mdns` in the 2.js [example](https://github.com/libp2p/js-libp2p/blob/72f37acd4a54bf5c3b67647d1723f556a59a43e5/examples/discovery-mechanisms/2.js)
When I have gathered a working sample, I will push it here if it may help.

**Comment by vasco-santos** [comment]
I created #665 that solves what was discussed here. I hope the visibility for the modules being required is better now.

Per #576 we have to get the configuration more obvious and easy for everyone, and not require users to read a bunch of documents for getting started.
