### ISSUE TITLE
Either libp2p-in-the-browser, GETTING_STARTED.md, or both are wrong

### ISSUE THREAD

**Issue by mcclure** [libp2p/js-libp2p#750]
Type: Documentation issue

I upgraded my [libp2p with preact](https://github.com/mcclure/ts-hello/tree/libp2p-preact) sample code to 0.29.0. My guides for upgrading to the new version were the "[libp2p-in-the-browser](https://github.com/libp2p/js-libp2p/blob/0.29.x/examples/libp2p-in-the-browser/index.js)" example in the repo and the [GETTING_STARTED.MD](https://github.com/libp2p/js-libp2p/blob/0.29.x/doc/GETTING_STARTED.md) file in the repo. I encountered two problems.

1. **libp2p-in-the-browser and GETTING_STARTED.MD no longer agree**. 

    1. Different methods for peer:connect. GETTING_STARTED.MD uses

            node.on('peer:connect', (peer) => {
              console.log('Connected to %s', peer.id.toB58String()) // Log connected peer
            })

        Whereas libp2p-in-the-browser uses

            libp2p.connectionManager.on('peer:connect', (connection) => {
              log(`Connected to ${connection.remotePeer.toB58String()}`)
            })

        node and libp2p are the same object. However, libp2p-in-the-browser calls `on` on a different object (connectionManager vs directly on libp2p) and the signatures are different (peer object vs connection object).

        Based on testing, I think the libp2p-in-the-browser approach is right and the GETTING_STARTED approach is wrong. But if both of these are valid, then GETTING_STARTED.md would be a great place to describe how you have two options, what the difference is, and where the object documentation for "libp2p" and "connectionManager" are so I can read more.

    2. Different configuration

        GETTING_STARTED uses an "autodial" parameter that libp2p-in-the-browser does not use. Also libp2p-in-the-browser indexes its "bootstrap" key as a string whereas GETTING_STARTED uses a [Bootstrap.tag] constant.

        In my testing, I think setting "autodial" broke things, but it was hard to tell. In any case, libp2p auto-connects without "autodial" being set to anything. As before, if "autodial" is optional but you are including it anyway for some reason, GETTING_STARTED would be a great place to describe why seemingly redundant options exist (string vs .tag, autodial:true does seemingly nothing) and why you might choose one of these seemingly redundant options over the other.

2. libp2p-in-the-browser potentially has many uncaught exceptions (could not reproduce?)

    On my first test with npm install && npm start of the libp2p-in-the-browser example from git bbf8ef706 , I got hundreds of copies of a single uncaught exception in the console. I accidentally closed the tab and on repeat tests I did not see the uncaught exception. I don't see the uncaught exception in my own test program. Probably you can ignore this unless it comes up again, maybe something was wrong in the npm start test webserver >_>

**Comment by vasco-santos** [comment]
Hello @mcclure 

> My guides for upgrading to the new version were the "libp2p-in-the-browser" example in the repo and the GETTING_STARTED.MD file in the repo. 

We have been doing migration guides for upgrading, which should be the documents used: https://github.com/libp2p/js-libp2p/tree/master/doc/migrations

1. 
> libp2p-in-the-browser and GETTING_STARTED.MD no longer agree.

You are right. I will PR the GETTING_STARTED.md with the new API. This change was introduced by [`libp2p@0.28`](https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.27-v0.28.md#events). 
While we should guarantee that all the docs are updated, I think the best place to see the API docs is the [API documentation doc](https://github.com/libp2p/js-libp2p/blob/master/doc/API.md).

> GETTING_STARTED uses an "autodial" parameter that libp2p-in-the-browser does not use. Also libp2p-in-the-browser indexes its "bootstrap" key as a string whereas GETTING_STARTED uses a [Bootstrap.tag] constant.

The GETTING_STARTED  uses the autoDial option to provide clarity. However, the browser example also uses that option as `js-libp2p` currently has it [enabled by default](https://github.com/libp2p/js-libp2p/blob/master/src/config.js#L44). You can read more about it in [PEER_DISCOVERY.md](https://github.com/libp2p/js-libp2p/blob/master/doc/PEER_DISCOVERY.md). Regarding the key, [Bootstrap.tag] computes to "bootstrap". We moved away from using the strings directly because it was not clear where that key came from. We missed that example, I will change it to use the tag.

If you are experiencing any issue let me know what is happening, but as previously mentioned, unless you say that the autoDial is disabled, it will be enabled.

2. libp2p-in-the-browser potentially has many uncaught exceptions (could not reproduce?)

Let me know if you can replicate it

**Comment by mcclure** [comment]
The migration guides look great, thanks for calling my attention to that.
