### ISSUE TITLE
Question: how is flow control handled?

### ISSUE THREAD

**Issue by chafey** [libp2p/js-libp2p#767]
- **Version**: 0.29.0
- **Platform**: Linux
- **Subsystem**:

#### Description: How is flow control is handled by libp2p when writing to a stream? 

My application can write to a libp2p stream much faster than the network can send the data and I am curious how flow control works with the libp2p streams.  I am using it-pipe and it-length-prefixed which are separate libraries but also commonly used with libp2p so the question applies to them too.  Basically I want to avoid running out of memory when sending a lot of data to a slow client.  Thanks for any information!

#### Steps to reproduce the error:

N/A

**Comment by vasco-santos** [comment]
Hey @chafey ,

I think what you want to know is related to libp2p multiplexers. You can read about it in the spec, more precisely [libp2p/specs/mplex#implementation-notes](https://github.com/libp2p/specs/tree/master/mplex#implementation-notes). Anyway, I am not entirely sure if we are currently doing this in the JS implementation per [libp2p/js-libp2p-mplex#85](https://github.com/libp2p/js-libp2p-mplex/issues/85). If you would like to double check it, it would be super helpful.

Also, `it-pipe` and `it-length-prefixed` were implemented by core contributors of the libp2p and IPFS projects for simplifying async iterators usage.

As a side note, we highly recommend questions to be asked in [discuss.libp2p.io](https://discuss.libp2p.io/) instead of github issues. This will easily help other people looking for already answered questions and will also enable collaboration between the community. For other questions, please ask in the forum 🙏

**Comment by chafey** [comment]
Thanks for the quick response, I'll ask questions on the forum going forward
