### ISSUE TITLE
[testing] fix node 15/16 install due to npm 7 changes

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#790]
Node 15 includes npm 7 which now automatically installs peer dependencies by default, https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/. 

This change also affects how we're linking `libp2p` itself in the devDependencies to make integration testing with modules like gossipsub easier (as it requires libp2p as a peerDependency).

Ideally we'd remove the local integration testing of modules and instead run their test suites in CI and test only the core API in the `libp2p` test suite. In the immediate term we should find a workaround for `"libp2p": "."` being in the devDependencies.

**Comment by vasco-santos** [comment]
@jacobheun I would like to get to this soon, so that we can bump CI to 15 and have tests running in both active and current Node versions. It would be great to get to a migration path here before starting

Modules with libp2p as a peerDependency:
- [libp2p-gossipsub](https://github.com/ChainSafe/js-libp2p-gossipsub)
- [libp2p-floodsub](https://github.com/libp2p/js-libp2p-floodsub)
- [libp2p-delegated-content-routing](https://github.com/libp2p/js-libp2p-delegated-content-routing)
- [libp2p-delegated-peer-routing](https://github.com/libp2p/js-libp2p-delegated-peer-routing)
- [libp2p-kad-dht](https://github.com/libp2p/js-libp2p-kad-dht) -- NOT YET 

The main concern is that we will need to support node 14, which does not install the peer dependencies

**Comment by lidel** [comment]
(note from triage) nearly done, waiting for https://github.com/libp2p/js-libp2p/pull/866
