### ISSUE TITLE
Can I rewrite this thing in TypeScript?

### ISSUE THREAD

**Issue by james2mid** [libp2p/js-libp2p#858]
I'd like to learn more about libp2p because it's awesome.

I'd also like to improve my TS skills + type safety is a desirable thing to have for a framework as sophisticated as this one.

Thoughts? :)

**Comment by vasco-santos** [comment]
Hello @james2mid 

We currently generate typescript declaration files on release, using types defined in jsdocs per #802 , so that libp2p users within typescript projects can use it easily. However, we are not looking for an entire rewrite of the codebase to typescript for 2 main reasons:
- time needed to so such a major revamp to all libp2p modules, which would mean more important features would not be done
- from a contribution perspective, it will be easier to contribute to libp2p as a JS project because all TS developers know JS, but not all JS developers know TS.

If you are still interested in helping out with other types of tasks let us know. There are a lot of issues labeled with `ready` and `easy` that you can have a look if you like

**Comment by james2mid** [comment]
I appreciate your reply. I'm keen to help out so I'll check out the available issues :)

Aside from the libp2p documentation, are there any learning resources you can recommend surrounding P2P and other related topics?

**Comment by vasco-santos** [comment]
> I appreciate your reply. I'm keen to help out so I'll check out the available issues :)

That would be super helpful. Let me know what would you like to get and we can discuss it further if you need. By the way, there is https://github.com/libp2p/js-libp2p/issues/659 and https://github.com/libp2p/js-libp2p/issues/830 in the context of adding types to jsdocs to create type declarations on build that you can have a look if you are interested in typescript thematic.

> Aside from the libp2p documentation, are there any learning resources you can recommend surrounding P2P and other related topics?

Have a look at this issue: https://github.com/libp2p/libp2p/issues/56 It has a lot of nice resources for the P2P space
