### ISSUE TITLE
Be a state machine. Just like js-ipfs :) 

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p#98]

**Comment by diasdavid** [comment]
@pgte is this still something you would like to pursue?

**Comment by pgte** [comment]
Yes.

**Comment by lgierth** [comment]
What does this entail? Is it something that other libp2p impls should be doing too?

**Comment by diasdavid** [comment]
@lgierth not at all. It is just how the libp2p Node in JS changes its state.

**Comment by diasdavid** [comment]
@pgte you have a ton of experience on this and have pointed out multiple issues with the current state-machine in js-ipfs. Do you have any recommendations? Modules to use, examples to take inspiration from so that we don't fall in the same thing? I want to implement it asap for #159

**Comment by pgte** [comment]
@diasdavid I think it can be boiled down to this:

* define a FSM (states and transitions) for a libp2p node
* let the user commands drive transitions of the state machine
* act on state changes instead of user commands

Some states transitions are initiated by the machine itself. Apply the same principle: do not act directly, only start transitions, decoupling state transition from handling the state transition. This only should allow you to escape some nasty bugs and require less verification and synchronisation.

As for the library, I like https://www.npmjs.com/package/fsm-event 's API.

Any more pointers you would like?

**Comment by pgte** [comment]
Ha, also another think, to your consideration:
(This doesn't apply directly to libp2p, I think, but can perhaps be translated to IPFS more directly.)

Allow operations while offline. If the operation requires the node to be online, wait until it is inline instead of failing.
For instance, pubsub publish can perhaps fail silently if the node is offline (since the API offers no delivery guarantees).

While, OTOH, the `file.get(cid)` can be postponed to when the node is online.

This would allow a more friendly programming style, similar to many database drivers out there, where we don't need to wait until we connect before issuing commands or queries.

**Comment by diasdavid** [comment]
Thank you! We use fsm-event in js-ipfs https://github.com/ipfs/js-ipfs/blob/master/src/core/state.js#L7 but I know you had some issues with how it was implemented. Could you elaborate on those?

**Comment by pgte** [comment]
Sure. As an example, let's see `ipfs.start()`: https://github.com/ipfs/js-ipfs/blob/master/src/core/components/start.js

It's confounding [issuing the state transition](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/start.js#L28) and [implementing the state transition](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/start.js#L30-L51).

Sine it's not driven by the FSM, it [has to validate state transition](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/start.js#L23-L25) .

Also, [emitting state transitions](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/start.js#L19) to the user could be generalised.

This would allow, for instance be forgiving in issuing transitions. For instance, double starts can be easily handled by using the following state and transitions:

```
(stopped) -> start() -> (starting)
(starting) -> start() -> (starting)
(starting) -> started() -> (started)
```

**Comment by pgte** [comment]
If a command is asynchronous, it can implemented by:

* commanding the transition
* waiting until the desired state has been reached

Pseudo-code:

```js
  start (cb) {
    this.state.start()
    this.state.waitForOrError('started', cb)
  }
```

**Comment by pgte** [comment]
(in this last example, an `error` would be a special state that signals an irrecoverable error.

**Comment by jozanza** [comment]
I'm interesting in helping out with this issue. What's the best way to get involved? :)
